import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="bg-[#141414] text-[#fffefe]">
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
